### ISSUE TITLE
missing evaluate.py

### ISSUE THREAD

**Issue by liuguilin1225** [meteorshowers/hed-pytorch#1]
Thanks for providing this code. I am wondering where the evaluate.py is?

**Comment by xwjabc** [comment]
+1

**Comment by xwjabc** [comment]
> Thanks for providing this code. I am wondering where the evaluate.py is?

Recently I wrote a PyTorch version of HED (with evaluation code) based on meteorshowers' code: https://github.com/xwjabc/hed
You can give it a try.

**Comment by tuqiangwang** [comment]
花里胡哨，文件都不全，还来丢人现眼
